### ISSUE TITLE
Polygons ignore style options when snogylop is included.

### ISSUE THREAD

**Issue by NathanMOlson** [ebrelsford/Leaflet.snogylop#10]
Here is a test case.  I am trying to draw a red polygon with no border.  It works without snogylop, but when I include snogylop the polygon is blue with a border.  This example uses leaflet 1.0.3 and snogylop 0.3.1.

[snogylop_test.zip](https://github.com/ebrelsford/Leaflet.snogylop/files/1024240/snogylop_test.zip)

**Comment by ebrelsford** [comment]
@NathanMOlson thanks for letting me know. I don't tend to create polygons that way so I hadn't tested for it. Try `v0.3.2`, it should work for you.

In the future if you can throw examples into something like [jsbin](http://jsbin.com/) or a [gist](https://gist.github.com/) it's easier for the person looking at the code.

**Comment by NathanMOlson** [comment]
Great, thanks! Fixed in 0.3.2.
