### ISSUE TITLE
Make toGeoJSON() return original geoJSON

### ISSUE THREAD

**Issue by cyrilchapon** [ebrelsford/Leaflet.snogylop#12]
On each layer, `.toGeoJSON()` return actual inverted latLngs instead of original ones

I think it's because internaly, leaflet [uses `this._latLngs` instead of `this.getLatLngs()`](https://github.com/Leaflet/Leaflet/blob/1120c46ed9c57ea4fcb3618cfceef5b90160b057/src/layer/GeoJSON.js#L333)

**Comment by ebrelsford** [comment]
Good point. I agree we should support `toGeoJSON()` and will be looking into it soon.

**Comment by cyrilchapon** [comment]
Temporary fallback: using `layer.feature` instead of `layer.toGeoJSON()`

**Comment by cyrilchapon** [comment]
Same for `getBounds()`

**Comment by ebrelsford** [comment]
@cyrilchapon These should both be fixed in `master` now, mind trying against that? If it works okay I can publish a new version. Thanks again for the reports.

**Comment by cyrilchapon** [comment]
Trying tomorow.

Thanks

Le 21 juin 2017 à 22:25, Eric Brelsford <notifications@github.com<mailto:notifications@github.com>> a écrit :


@cyrilchapon<https://github.com/cyrilchapon> These should both be fixed in master now, mind trying against that? If it works okay I can publish a new version. Thanks again for the reports.

**Comment by cyrilchapon** [comment]
`getBounds()` works, both on parent GeoJSON and on inverted polygon layer.

`ToGeoJSON()` doesn't, neither on the parent GeoJSON and on inverted polygon layer.

**Comment by ebrelsford** [comment]
@cyrilchapon can you give me more details about `toGeoJSON()` not working? Can you confirm that you're using Leaflet > 1.0.0? And the current version of this plugin at `master`?

For me, calling `toGeoJSON()` on an inverted polygon works as expected, as in [this example](https://github.com/ebrelsford/Leaflet.snogylop/blob/master/examples/1.0/polygon_togeojson.html).

If you can post a code example with it not working that would be appreciated.

**Comment by cyrilchapon** [comment]
I bower installed the last commit on master, and leaflet 1.0.0,
I'll try

**Comment by ebrelsford** [comment]
@cyrilchapon I published a new version (`0.3.4`), would you mind trying against that when you have a chance? If it doesn't work would you mind sending details about what you expected to get as output and what you got instead?

**Comment by TheGreatRefrigerator** [comment]
Hi, i am also struggeling with the `toGeoJSON()` function. It seems to overwrite some functionality of the original Leaflet `toGeoJSON()`.
I have setup an example in my fork of your repository.
https://github.com/TheGreatRefrigerator/Leaflet.snogylop/blob/master/examples/1.0/polygon_togeojson_example.html
If you uncomment the inclusion of your script, you can see how the generated GeoJson Polygon coordinates contain `NaN` values.

My workaround for now is commenting the `toGeoJSON()` function in your script in my bower_dependencies..
But it would be great if you could take another look at it :)

**Comment by ebrelsford** [comment]
@TheGreatRefrigerator Thanks for the concrete example, that helps. I made some changes on `master` that makes your example work and I think will improve things generally. Give that a shot and let me know? If it works I'll publish a new version since we're due for one.

**Comment by TheGreatRefrigerator** [comment]
@ebrelsford Thank you for still working on this.
Changes are working like a charm :sparkles:

**Comment by ebrelsford** [comment]
Excellent, I'll push a new version out then.

**Comment by ebrelsford** [comment]
Fixed in `v0.4.0`, which was published to npm.
