### ISSUE TITLE
L.LineUtil._flat is deprecated 

### ISSUE THREAD

**Issue by pdvorchik** [ebrelsford/Leaflet.snogylop#14]
`L.LineUtil._flat` is now deprecated and leads to a warning in the console.  This significantly slows down load time.  

We should be using http://leafletjs.com/reference-1.3.0.html#lineutil-isflat instead.

**Comment by chriszrc** [comment]
Nice! Will this go out in a release, so we can all update from npm?

**Comment by ebrelsford** [comment]
Yes it's in `v0.4.0` which I just published to npm.

**Comment by chriszrc** [comment]
Update is working great, thanks!
