### ISSUE TITLE
Stroke width weird effect

### ISSUE THREAD

**Issue by cyrilchapon** [ebrelsford/Leaflet.snogylop#7]
Hello. Thanks for this useful lib :)

When setting a weight property, this looks strange :

![edge_errorl](https://cloud.githubusercontent.com/assets/10728426/19932925/053774cc-a112-11e6-9fd0-46946a845e9c.png)

(then line is not exactly on the edge of the polygon)

**Comment by ebrelsford** [comment]
@cyrilchapon glad you find it useful!

Can you provide a better screenshot or--better yet--a working example where this is a problem? And can you elaborate on "looks strange"? It's rather difficult to tell from this screenshot what is going on and what the preferred outcome is.

**Comment by cyrilchapon** [comment]
Pretty hard to have a better screenshot while this require a violent zoom to show.

On my screenshot you see this polygon :

```
function getFilterOverlayLayer(){
  return L.geoJson(null, {
    invert: true,
    style: {
      color: "#000",
      weight: 2,
      fillOpacity: 0.7,
      clickable: false
    }
  });
}
```

As you can see, the "stroke" position is not realy on the edge, but a 1px padding is added. If I set `weight: 20` it produces the following :

![edge_error2](https://cloud.githubusercontent.com/assets/10728426/19967564/2c0eb604-a1d1-11e6-941f-e8948a6a4f04.png)

The padding seems to be half the "stroke width", so I guess 10px here.

**Comment by ebrelsford** [comment]
@cyrilchapon it seems like you're describing how Leaflet styles polygons. I would recommend looking more at Leaflet styles and SVG styles.

Is there some way that this plugin would fix that?

**Comment by cyrilchapon** [comment]
Hum ok.

Verified this is same behavior with non-inverted polygons.

Sorry for your time. And thanks 😃
