### ISSUE TITLE
Multipolygon with hole ?

### ISSUE THREAD

**Issue by sylvain-m** [ebrelsford/Leaflet.snogylop#9]
Hi,
I hope this is not a bad use of my part, but I have a problem with the plugin.
Here is my problem: I want to invert a polygon (multipolygon) that has a hole.
But the hole does not appear when polygon is inverted with the plugin.

A drawing may be more understandable (especially since my level of English is very low) : 
![multipolygon_with_hole_slogylop](https://cloud.githubusercontent.com/assets/11629210/26209541/636c6b44-3bed-11e7-8e5f-6a765f03c660.png)

Have you ever faced this problem ?

**Comment by sylvain-m** [comment]
(I first forgot to thank you for this plugin which is really very useful and very easy to use!)

**Comment by ebrelsford** [comment]
@sylvain-m Thanks for letting me know. Which version of Leaflet and the plugin are you using? Can you post an example dataset?

**Comment by sylvain-m** [comment]
Thank you for considering this issue,
Here is an example map with the problem in question:
[http://149.202.129.102/pnrnm/leaflet_snogylop.php](http://149.202.129.102/pnrnm/leaflet_snogylop.php)
The perimeter of the study area has a hole in the middle (due to municipalities that do not engage to the project).
In this map, the same perimeter is displayed twice: inverted (mask) and not inverted.
If you need GeoJson, it is generated in PHP at this address : [http://149.202.129.102/pnrnm/geojson_pnrnm.php](http://149.202.129.102/pnrnm/geojson_pnrnm.php)

For the version of Leaflet, it is: 0.7.3
For the Snogylop plugin, I forgot to note the version, and I see that this is not the last one.
I will try with the latest version soon.

Thank you in advance if you manage to take into account this scenario!

**Comment by sylvain-m** [comment]
Same problem with `Leaflet 1.0.3` and `Snogylop 0.3.0` : 
http://149.202.129.102/pnrnm/leaflet_snogylop_last.php

**Comment by ebrelsford** [comment]
Thanks for the update! I'd like the plugin to support this use case, but I'll have to look more into how leaflet handles holes in polygons in holes in polygons.

**Comment by ebrelsford** [comment]
@sylvain-m I just released v0.3.1, mind trying that and letting me know how that works? (Commit 4680c58).

**Comment by sig-pnrnm** [comment]
Yeees ! It works : http://149.202.129.102/pnrnm/leaflet_snogylop_last.php
👍 
Great !!!
Thanks a lot ! :)

**Comment by ebrelsford** [comment]
Yay glad to help!

**Comment by sylvain-m** [comment]
Sorry, i was logged in with an other account, but it is the same Sylvain here ;-)
Thanks !
